# Generated by Django 5.0 on 2023-12-30 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expen', '0002_expensescategory_remove_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
