# Generated by Django 5.0 on 2024-01-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expen', '0003_userprofile_activation_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='fullname',
            new_name='username',
        ),
    ]
