# Generated by Django 5.0 on 2024-01-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expen', '0004_rename_fullname_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
