# Generated by Django 5.0 on 2024-01-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expen', '0005_userprofile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
